#!/usr/bin/env bash

# Install tmux plugin manager
# https://github.com/tmux-plugins/tpm/blob/master/docs/automatic_tpm_installation.md

# tmux

if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"

mv ~/.tmux.conf ~/.tmux.conf.backup || echo "tmux config not found!!!"
stow tmux

# fish

if ! command -v &> /dev/null
then
  wget https://github.com/fish-shell/fish-shell/releases/download/3.6.1/fish-3.6.1.tar.xz
  tar xvzf fish-3.6.1.tar.xz
  cd fish
  cmake .; make; sudo make install
  cd ..
fi

mv ~/.config/fish ~/.config/fish.backup || echo "fish config not found!!!"
stow fish

# nvim

if ! command -v nvim &> /dev/null
then
  wget https://github.com/neovim/neovim/releases/download/v0.9.4/nvim.appimage
  chmod u+x nvim.appimage
  ./nvim.appimage --appimage-extract || echo "Not extractable..."
  mv squashfs-root/usr/bin/nvim /usr/bin/local/nvim
fi
mv ~/.config/nvim ~/.config/nvim.backup || echo "nvim config not found!!!"
stow nvim
