#!/usr/bin/env bash

mv ~/.tmux.conf ~/.tmux.conf.backup || echo "tmux config not found!!!"
stow tmux

mv ~/.config/fish ~/.config/fish.backup || echo "fish config not found!!!"
stow fish

mv ~/.config/nvim ~/.config/nvim/backup || echo "nvim config not found!!!"
stow nvim
