---
- name: Ensure the symlink source exists
  stat:
    path: "{{ source }}"
  register: source_check

- name: Fail if the symlink source does not exist
  fail:
    msg: "The symlink source {{ source }} does not exist."
  when: not source_check.stat.exists

- name: Check if destination exists
  stat:
    path: "{{ destination }}"
  register: dest_check

- name: Remove existing symlink if present
  file:
    path: "{{ destination }}"
    state: absent
  # when: not dest_check.stat.exists and dest_check.stat.islnk
  when: dest_check.stat.exists and dest_check.stat.islnk | default(false)

- name: Backup existing file or directory if present and not a symlink
  command: cp -a "{{ destination }}" "{{ destination }}.bak"
  #copy:
  #  src: "{{ destination }}"
  #  dest: "{{ destination }}.bak"
  #  remote_src: yes
  when: dest_check.stat.exists and not dest_check.stat.islnk | default(false)

- name: Remove original file or directory after backup
  file:
    path: "{{ destination }}"
    state: absent
  when: dest_check.stat.exists and not dest_check.stat.islnk

- name: Create symlink
  file:
    src: "{{ source }}"
    dest: "{{ destination }}"
    state: link
