---
- name: Install Azure CLI on Debian-based systems
  become: true
  block:
    - name: Add Microsoft signing key
      apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
        state: present

    - name: Add Azure CLI repository
      apt_repository:
        repo: "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ {{ ansible_distribution_release }} main"
        state: present
        filename: azure-cli

    - name: Install Azure CLI
      apt:
        name: azure-cli
        state: present
        update_cache: yes
  when: ansible_facts['os_family'] == 'Debian'
  tags:
    - azure
    - install
    - debian

- name: Install Azure CLI on macOS
  homebrew:
    name: azure-cli
    state: present
  when: ansible_facts['os_family'] == 'Darwin'
  tags:
    - azure
    - install
    - macos

# - name: Initialize Azure CLI configuration
#   command: az login
#   register: az_login_result
#   changed_when: false
#   failed_when: false
#   tags:
#     - azure
#     - config

# - name: Display Azure CLI login result
#   debug:
#     msg: "{{ az_login_result.stdout_lines }}"
#   when: az_login_result.rc == 0
#   tags:
#     - azure
#     - config

# - name: Warn if Azure CLI login failed
#   debug:
#     msg: "Azure CLI login failed. Please run 'az login' manually to configure."
#   when: az_login_result.rc != 0
#   tags:
#     - azure
#     - config
