---
- name: Install Bazel on Darwin
  homebrew:
    name: bazel
    state: present
  when: ansible_facts['os_family'] == 'Darwin'
  tags:
    - bazel
    - install
    - macos

- name: Install Bazel on Ubuntu
  become: true
  apt:
    deb: https://github.com/bazelbuild/bazel/releases/download/6.2.1/bazel_6.2.1-linux-x86_64.deb
  when: ansible_facts['os_family'] == 'Debian'
  tags:
    - bazel
    - install
    - ubuntu
    - sudo

- name: Add Bazel apt repository
  become: true
  apt_repository:
    repo: deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8
    state: present
    filename: bazel
  when: ansible_facts['os_family'] == 'Debian'
  tags:
    - bazel
    - install
    - ubuntu
    - sudo

- name: Install Bazel dependencies on Ubuntu
  become: true
  apt:
    name:
      - openjdk-11-jdk
      - g++
      - unzip
      - zip
    state: present
  when: ansible_facts['os_family'] == 'Debian'
  tags:
    - bazel
    - install
    - ubuntu
    - sudo
