---
- name: Install kubectl on Darwin
  homebrew:
    name: kubectl
    state: present
  when: ansible_facts['os_family'] == 'Darwin'

- name: Get the latest stable kubectl version
  uri:
    url: https://dl.k8s.io/release/stable.txt
    return_content: yes
  register: kubectl_version
  when: ansible_facts['os_family'] == 'Debian'

- name: Get the checksum for the kubectl binary
  uri:
    url: "https://dl.k8s.io/{{ kubectl_version.content }}/bin/linux/amd64/kubectl.sha256"
    return_content: yes
  register: kubectl_checksum
  when: ansible_facts['os_family'] == 'Debian'

- name: Download the kubectl binary with checksum verification
  become: true
  get_url:
    url: "https://dl.k8s.io/{{ kubectl_version.content }}/bin/linux/amd64/kubectl"
    dest: /usr/local/bin/kubectl
    checksum: "sha256:{{ kubectl_checksum.content }}"
    mode: "0755"
    owner: root
    group: root
  tags:
    - sudo
  when: ansible_facts['os_family'] == 'Debian'
