---
- name: Configure Neovim
  import_role:
    name: config_linker
  vars:
    source: "{{ ansible_env.PWD }}/config/nvim"
    destination: "{{ ansible_env.HOME }}/.config/nvim"
  tags:
    - neovim
    - config
- name: Download Neovim AppImage
  get_url:
    url: "https://github.com/neovim/neovim/releases/latest/download/nvim.appimage"
    dest: "/tmp/nvim.appimage"
    mode: '0755'
  when: ansible_facts['os_family'] == 'Debian'
  tags:
    - neovim
    - ubuntu

- name: Extract AppImage
  command: "/tmp/nvim.appimage --appimage-extract"
  args:
    chdir: "/tmp"
    creates: "/tmp/squashfs-root"
  when: ansible_facts['os_family'] == 'Debian'
  tags:
    - neovim
    - ubuntu

- name: Move Neovim binary to /usr/local/bin
  become: true
  copy:
    src: "/tmp/squashfs-root/usr/bin/nvim"
    dest: "/usr/local/bin/nvim"
    mode: '0755'
    remote_src: yes
  when: ansible_facts['os_family'] == 'Debian'
  tags:
    - neovim
    - ubuntu

- name: Clean up temporary files
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/tmp/nvim.appimage"
    - "/tmp/squashfs-root"
  when: ansible_facts['os_family'] == 'Debian'
  tags:
    - neovim
    - ubuntu

- name: Install Neovim on macOS using Homebrew
  homebrew:
    name: neovim
    state: present
  when: ansible_facts['os_family'] == 'Darwin'
  tags:
    - neovim
    - macos
    - brew

- name: Verify Neovim installation
  command: "nvim --version"
  register: nvim_version_output
  changed_when: false
  tags:
    - neovim

- name: Display installed Neovim version
  debug:
    msg: "Neovim version installed: {{ nvim_version_output.stdout_lines[0] }}"
  tags:
    - neovim


