---
- name: Install Pants on macOS
  homebrew:
    name: pants
    state: present
  when: ansible_facts['os_family'] == 'Darwin'
  tags:
    - pants
    - install
    - macos

- name: Install Pants on Ubuntu
  become: true
  shell: |
    curl --proto '=https' --tlsv1.2 -fsSL https://static.pantsbuild.org/setup/get-pants.sh | bash
  args:
    creates: /usr/local/bin/pants
  when: ansible_facts['os_family'] == 'Debian'
  tags:
    - pants
    - install
    - ubuntu
