---
- name: Install Python on Darwin
  homebrew:
    name: python
    state: present
  tags:
    - brew
    - macos
  when: ansible_facts['os_family'] == 'Darwin'

- name: Install Python 3 and related packages
  become: true
  apt:
    name:
      - python3
      - python3-pip
      - python3-venv
    state: present
  tags:
    - sudo
  when: ansible_facts['os_family'] == 'Debian'