---

- name: Configure Tmux
  import_role:
    name: config_linker
  vars:
    source: "{{ ansible_env.PWD }}/config/tmux/.tmux.conf"
    destination: "{{ ansible_env.HOME }}/.tmux.conf"
  tags:
    - tmux
    - config

- name: Install Tmux on Debian-based systems
  become: true
  apt:
    name: tmux
    state: present
  when: ansible_facts['os_family'] == 'Debian'
  tags:
    - tmux
    - apt
    - ubuntu
    - sudo

- name: Install Tmux on macOS
  homebrew:
    name: tmux
    state: present
  when: ansible_facts['os_family'] == 'Darwin'
  tags:
    - tmux
    - brew
    - macos

- name: Verify Tmux installation
  command: "tmux -V"
  register: tmux_version_output
  changed_when: false
  tags:
    - tmux

- name: Display installed Tmux version
  debug:
    msg: "Tmux version installed: {{ tmux_version_output.stdout }}"
  tags:
    - tmux
