---
- name: Install Visual Studio Code on Ubuntu
  become: true
  apt:
    deb: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64
  when: ansible_facts['os_family'] == 'Debian'
  tags:
    - vscode
    - install
    - ubuntu

- name: Install Visual Studio Code on macOS
  homebrew_cask:
    name: visual-studio-code
    state: present
  when: ansible_facts['os_family'] == 'Darwin'
  tags:
    - vscode
    - install
    - macos
- name: Install VS Code extensions
  tasks:
    - name: Install VS Code extensions
      command: code --install-extension "{{ item }}"
      loop:
        - antiantisepticeye.vscode-color-picker
        - asvetliakov.vscode-neovim
        - ban.spellright
        - batisteo.vscode-django
        - bibhasdn.django-html
        - bigonesystems.django
        - donjayamanne.python-environment-manager
        - donjayamanne.python-extension-pack
        - donjayamanne.githistory
        - eamodio.gitlens
        - github.copilot
        - github.copilot-chat
        - ms-python.python
        - ms-toolsai.jupyter
        - ms-vscode-remote.remote-containers
        - ms-vscode-remote.remote-ssh
        - ms-vscode-remote.remote-ssh-edit
        - ms-vscode-remote.remote-wsl
        - ms-vscode-remote.vscode-remote-extensionpack
        - ms-vscode.remote-explorer
        - ms-vscode.remote-server
        - quarto.quarto
        - redhat.vscode-yaml
        - streetsidesoftware.code-spell-checker
        - redhat.ansible
        - visualstudioexptteam.vscodeintellicode
        - vscode-icons-team.vscode-icons
        - waderyan.gitblame
      tags:
        - vscode
        - extensions
        - install