---
- name: Install zoxide on Debian-based systems
  become: true
  apt:
    name: zoxide
    state: present
  when: ansible_facts['os_family'] == 'Debian'
  tags:
    - zoxide
    - install
    - debian

- name: Install zoxide on macOS
  homebrew:
    name: zoxide
    state: present
  when: ansible_facts['os_family'] == 'Darwin'
  tags:
    - zoxide
    - install
    - macos

- name: Check if zoxide is sourced in fish config
  command: grep -q "zoxide init fish" ~/.config/fish/config.fish
  register: zoxide_fish_check
  changed_when: false
  failed_when: false
  tags:
    - zoxide
    - config

# - name: Add zoxide to fish config if not present
#   lineinfile:
#     path: ~/.config/fish/config.fish
#     line: 'zoxide init fish | source'
#     state: present
#   when: zoxide_fish_check.rc != 0
#   tags:
#     - zoxide
#     - config

# - name: Check if zoxide is sourced in bash config
#   command: grep -q "eval \"\$(zoxide init bash)\"" ~/.bashrc
#   register: zoxide_bash_check
#   changed_when: false
#   failed_when: false
#   tags:
#     - zoxide
#     - config

# - name: Add zoxide to bash config if not present
#   lineinfile:
#     path: ~/.bashrc
#     line: 'eval "$(zoxide init bash)"'
#     state: present
#   when: zoxide_bash_check.rc != 0
#   tags:
#     - zoxide
#     - config

# - name: Check if zoxide is sourced in zsh config
#   command: grep -q "eval \"\$(zoxide init zsh)\"" ~/.zshrc
#   register: zoxide_zsh_check
#   changed_when: false
#   failed_when: false
#   tags:
#     - zoxide
#     - config

# - name: Add zoxide to zsh config if not present
#   lineinfile:
#     path: ~/.zshrc
#     line: 'eval "$(zoxide init zsh)"'
#     state: present
#   when: zoxide_zsh_check.rc != 0
#   tags:
#     - zoxide
#     - config
